version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=StrongPassw0rd!
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
      - ./data:/data
      - ./scripts:/scripts
    healthcheck:
      test: ["CMD-SHELL", "exit 0"]

  init-db:
    image: mcr.microsoft.com/mssql-tools
    container_name: init-db
    depends_on:
      sqlserver:
        condition: service_healthy
    volumes:
      - ./data:/data
      - ./scripts:/scripts
    entrypoint: ["/bin/bash", "-c"]
    command:
      - |
        echo "Waiting for SQL Server to be ready...";
        sleep 10;
        echo "Initializing database...";
        /opt/mssql-tools/bin/sqlcmd -S sqlserver -U sa -P StrongPassw0rd! -i /scripts/init_db.sql

volumes:
  sqlserver_data:
